### ISSUE TITLE
how can i update me old RetroPie-joystick-selection

### ISSUE THREAD

**Issue by Guitarans** [meleu/RetroPie-joystick-selection#13]
Hi there. i really think this is a Great Add-on to the retropie. I use it alot.
i am quite new in this, but how do i update my joystick-selection?

thanks alot..

is there anyway that i can support your work?

**Comment by meleu** [comment]
Thanks for the compliments. :-)

To update you actually have to reinstall it. But I'm planning to implement some improvements about it soon and will let you know.

Regarding to supporting, a donation to the RetroPie project would be much appreciated. ;-)

**Comment by meleu** [comment]
@Guitarans check the README, now it's easy to update the joystick-selection tool.
