### ISSUE TITLE
sorry to say it, but this is what i get when i try to install it?

### ISSUE THREAD

**Issue by Guitarans** [meleu/RetroPie-joystick-selection#17]
pi@retropie:~ $ sudo wget https://raw.githubusercontent.com/meleu/RetroPie-joystick-selection/master/install.sh -o ~/RetroPie-Setup/scriptmodules/supplementary/joystick-selection.sh

pi@retropie:~ $ sudo ~/RetroPie-Setup/retropie_setup.sh
/home/pi/RetroPie-Setup/scriptmodules/supplementary/joystick-selection.sh: line 1: --2017-03-29: command not found
/home/pi/RetroPie-Setup/scriptmodules/supplementary/joystick-selection.sh: line 2: syntax error near unexpected token `('
/home/pi/RetroPie-Setup/scriptmodules/supplementary/joystick-selection.sh: line 2: `Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133'
Module /home/pi/RetroPie-Setup/scriptmodules/supplementary/joystick-selection.sh is missing valid rp_module_id
Module /home/pi/RetroPie-Setup/scriptmodules/supplementary/joystick-selection.sh is missing valid rp_module_desc

on a fresh retropie 4.2

**Comment by meleu** [comment]
Sorry to say it, but you aren't following the [Installation instructions](https://github.com/meleu/RetroPie-joystick-selection#installation) on README. ;-)

**Comment by meleu** [comment]
**Really sorry for that! And huge thanks for reporting it!**

I've fixed the [installation instructions](https://github.com/meleu/RetroPie-joystick-selection/blob/master/README.md#installation). Use `curl` to get the file (not wget).

BTW: wget works as well, but the right argument is a capital `-O`, and not `-o`.

**Comment by meleu** [comment]
Tested with `curl` and everything is fine here. I'm closing this issue but feel free to reopen if it isn't working for you.

**Comment by Guitarans** [comment]
:-) linux in a nutshell   o O ... ill give it a try.. Thanks for responding.
