### ISSUE TITLE
is there a way to add the joystick selector tool within each rom folder?

### ISSUE THREAD

**Issue by themailboxhere** [meleu/RetroPie-joystick-selection#23]
So, I have a system that I switch between arcade sticks, ps3, xbox360, steam controllers, etc... when you select a game system you are presented with the list of available games. I have created notes at the top of the game list by making empty files with the correct game extension which show up in the game list, for example: 

-supported controllers are the following-.nes
-arcade sticks, ps3, xbox360-.nes

those lines appear at the top of the list of games.

I would like to add your selector tool right underneath these lines so on the fly someone could set the config for the controller needed without going back to the retropie menu. For most things my ps3 controller works but for some things such as segaCD the ps3 controller is wonky, having my notes on top ensure someone who is playing my system grabs the appropriate controller, I would like them to easily navigate to the selector tool if at all possible.

**Comment by meleu** [comment]
The best way to achieve what you want is to choose a game and while on that launching screen press a button to enter the runcommand menu. And then go to User Menu -> joystick_selection.

It's an already implemented feature, if you don't have it you'll need to update the tool

**Comment by meleu** [comment]
as it's not an actual issue, I'm closing this. Feel free to continue the conversation, though.
