### ISSUE TITLE
CLI Install Causes Permissions Issues?

### ISSUE THREAD

**Issue by benjeffreys** [meleu/RetroPie-joystick-selection#27]
Hi there.

First of all, thank you for this. It's a great tool and has made my life a lot easier! 👍 

I just wanted to raise an issue that I've been seeing.

On initial installation, I get a bunch of permission denied errors. These errors look like this (the block is repeated multiple times):

```
grep: /opt/retropie/configs/mame-libretro/joystick-selection.cfg: Permission Denied
sed: can't read /opt/retropie/configs/mame-libretro/joystick-selection.cfg: Permission Denied
/opt/retropie/lib/inifuncs.sh: line 82:  /opt/retropie/configs/mame-libretro/joystick-selection.cfg: Permission Denied
```

**Screenshot:**
![img_3126](https://user-images.githubusercontent.com/625265/43518768-f3641ade-9584-11e8-9eb1-4e227803286c.jpg)

**To reproduce:**

Do a fresh install of Retropie 4.4 on a 16gb card.
Run this in a Raspberry Pi 3 Model B+.
Use F4 to quit from Emulationstation (once it boots).
Set up a USB controller.
Don't install any ROMs.
Install Joystick Selection using the suggested method:

```
curl https://raw.githubusercontent.com/meleu/RetroPie-joystick-selection/master/install.sh -o install.sh
bash install.sh
```

Restart Emulationstation.
Select "Joystick Selection" from the Retropie menu items.
Attempt to set "joystick selection by name" (throws permission errors).
Attempt to set global options (throws permission errors).

**The workaround (which is working so far) is:**
Go to Manage packages >> Manage experimental packages >> joystick-selection
Uninstall Joystick Selection.
Reboot system.
Go to Manage packages >> Manage experimental packages >> joystick-selection
Re-install Joystick Selection.
Now, "joystick selection by name" and the global / core configs work.

Not sure if I'm doing anything wrong? Examining the joystick-selection.cfg files that are initially written shows that they're owned by "root". Re-installing shows that they're owned by "pi".

Please let me know if you need any more info! Cheers!

**Comment by laseryuan** [comment]
In my case, there is no need to uninstall it. Just delete the file joystick-selection.cfg, then run ~/RetroPie-Setup/retropie_setup.sh to config

**Comment by sspencer10** [comment]
Same issue, but both suggestions do not work for me. joystick-selection.cfg gets recreated as root

**Comment by superfly851** [comment]
I'm having the same problem.  Tried the above solutions and did not work.  Recently did a full Retropie update which caused the problem.

**Comment by meleu** [comment]
can you guys try to uninstall it and then reinstall using the method I've put on the README a couple of days ago?
```
wget -O- "https://raw.githubusercontent.com/meleu/RetroPie-joystick-selection/master/install.sh" | sudo bash
```

**Comment by superfly851** [comment]
Thanks Melu,
I uninstalled it and reinstalled from source it in the retorpie menu and now it's working.  Not sure why it didn't work last time.  This time i left the Dragonrise arcade joystick unplugged and only had the 8Bitdo controller connected with bluetooth.  Not sure if that made a difference but it's working now.

**Comment by meleu** [comment]
then I'm closing this issue.
Feel free to reopen if you think it's still a problem.
