### ISSUE TITLE
Creation of junk directory with special characters

### ISSUE THREAD

**Issue by Sinistral2099** [meleu/RetroPie-joystick-selection#29]
Installation creates a directory called 'runcommand-menu?.' in /opt/retropie/configs/all/

This was done yesterday with RetroPie 4.4.2. It was a clean install. Raspbian was also fully updated.

**Comment by meleu** [comment]
it's intentional and it's not junk.
It lets you invoke the joystick selector in the runcommand menu (that screen shown right after chosing a game a before the emulator is launched).

Closing this issue. Feel free to reopen if you still think it's an issue (but please, provide more details).

**Comment by Sinistral2099** [comment]
Wrong.

> Since version 4.2.8 runcommand menu creates an option named User Menu where is possible to choose a custom script to launch. The custom scripts must be placed at /opt/retropie/configs/all/runcommand-menu and file name must end with .sh.

Yours does not do that. It creates a junk directory that cannot be deleted without passing a wild card. It doesn't create a directory that runcommand can use because of the ?. at the end.

Your script only works 50% at this point. Fix it or delete it.
