### ISSUE TITLE
Order if Joysticks are unplugged

### ISSUE THREAD

**Issue by CsCt00** [meleu/RetroPie-joystick-selection#31]
Hi! First of all, awesome tool! Love it!
Second, I have my retropie working on a raspberry on an arcade  that I made with its 2 corresponding sticks and buttons controllers (USB Delay Zero x2) . I also use extra controllers to play different consoles emulation (Like usb snes controllers, sega controllers, ps controllers) and I plug/unplug them as needed.
The thing is if I set an order method for every console, taking always the console controllers as primary, whenever I want to play a game without the console controllers and use the arcade controllers (stick/buttons) they don't work, obviously because the console controllers are not connected but still set as the #1 and #2 controllers in your tool.

If there any workaround for me to be able to:
* Use arcade controllers as #1 and #2 if no other controllers are plugged
* If a corresponding console control is plugged, then they should act as #1 / #2, leaving Arcade controls as #3 and #4.

Sorry for the long text, I'm not good at summarizing doubts.

Thanks in advance!

**Comment by cgmckeever** [comment]
@Cascote00 were you ever able to rectify this? Im have a pretty identical set up as well .. 
- couple dedicated sticks that never change ports (or in theory shouldnt)
- plug and smash controllers for the consoles

I found this project via https://retropie.org.uk/forum/topic/740/having-more-than-one-player-1/15 and it sounded like it would do graceful fallback. Im planning on trying this out and I can report back my findings.

**Comment by meleu** [comment]
hi guys!

@cgmckeever if you could confirm and report back it would be very appreciated. Thanks!

**Comment by cgmckeever** [comment]
@meleu so this is amazeballs. Using your utility, I can set the desired gamepad. If it is not plugged in, it does fallback to my dedicated joysticks.

The one thing that sort of flops is that _if_ (in my case there is) a `SYSTEM/retroarch.cfg` remap of a button - it uses that remap, which in my case was there because my joysticsk A and gamepad A dont align.

It'd be great if your tool could have a toggle to honor remapping or not in the config. 

I think the better solution for me to make this 100% balls-awesome is to get my USB Encoder better matched to the gamepads so I have to dick less with remaps and MORE GAME TIME!

**Comment by cgmckeever** [comment]
BAMMMM !!! after totally F'ing up my mappings trying to get this sorted out. Reverted to an backup image, manually changed `es_input` and some `autoconfs` got all the buttons aligned properly -- then installed this WONDERFUL PIECE OF SOFTWARE and now have graceful fallback to the dedicated joysticks or proper handling when USB's are switched in (using `name` mode is clutch)

THANK YOU

**Comment by meleu** [comment]
As a non-native speaker I didn't fully understand what being a clutch is, but I hope it's a good thing! :sweat_smile: 

@Cascote00, I'm closing this issue as solved, but feel free to reopen if you think it's still a problem.

**Comment by cgmckeever** [comment]
@meleu CLUTCH is like coming in at the last minute and saving the day!
