### ISSUE TITLE
Change via CLI

### ISSUE THREAD

**Issue by iamntz** [meleu/RetroPie-joystick-selection#32]
Hey guys. I just discovered this utility and is kind of awesome. It does exactly what it should, so is all good.

However, what I'm trying to achieve is: set a key combination to swap gamepad on the fly, withouth the need to go trough menus (mostly because the end user is not very tech savy).

While the key combination part is solved (by using triggerhappy), I'm not sure how/if I could this app to change via CLI.

So, any help in this direction?

Thanks!

**Comment by meleu** [comment]
What you wanna do is out of the scope of this project, sorry.
