### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by tkantor81** [meleu/RetroPie-joystick-selection#34]
ln: failed to create symbolic link '/home/pi/RetroPie/retropiemenu/joystick_selection.sh': Operation not permitted
cp: cannot stat '/opt/retropie/supplementary/joystick-selection/joystick_selection.sh': No such file or directory

How can I fix it manualy?

**Comment by meleu** [comment]
> ln: failed to create symbolic link '/home/pi/RetroPie/retropiemenu/joystick_selection.sh': Operation not permitted

Looks like something that happens when using a fat32 partition (or other filesystem that doesn't support symbolic links).

I'm closing this issue but feel free to reopen if you think it's still a problem.
