### ISSUE TITLE
Hanging on execution of install command line

### ISSUE THREAD

**Issue by Marcopolomint** [meleu/RetroPie-joystick-selection#41]
Dear Meleu,
unfortunately the install is doing something very strange when I try to execut the command line. It just hangs with the cursor flashing. It does not install the joystick-selection in the experimental packages list, even if I reboot. This is what is coming up when I run the command. Could it be something to do with the password being required?

mark@mark-VGN-TT11WN-B:~$ wget -O- "https://raw.githubusercontent.com/meleu/RetroPie-joystick-selection/master/install.sh" | sudo bash
[sudo] password for seallord: --2020-08-12 11:49:33--  https://raw.githubusercontent.com/meleu/RetroPie-joystick-selection/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 981 [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]     981  --.-KB/s    in 0s      

2020-08-12 11:49:33 (9.72 MB/s) - written to stdout [981/981]
""Blinking cursor""

At this point it appears to be doing nothing.

**Comment by meleu** [comment]
> Could it be something to do with the password being required?

yes. I suggest you to type your password and hit enter (even if the cursor doesn't look like in the right place).

**Comment by Marcopolomint** [comment]
OK, so I typed my password, it then tries to complete the operation, but this comes up:
(I'm surprised actually no-one else has this issue as you have to set a password by default and removing of the password from a SUDO command requires editing a system file)

bash: line 18: curl: command not found
Failed to install. Aborting...

**Comment by meleu** [comment]
you don't have the `curl` installed. I thought it was installed "by default" on RetroPie.

well, you can solve it with `sudo apt install curl`, and after installing it follow the steps to install the joystick-selection tool again.

**Comment by Marcopolomint** [comment]
Perfect Meleu, that's all that was wrong. All fixed now thankyou. So it looks like Ubuntu 20.04 LTS does not auto install curl!
I'm actually about to try a different install of Ubuntu on a standalone USB stick to plug into any machine so I can have a portable Retropie. I'll see if it does the same (i.e. not install curl).

**Comment by meleu** [comment]
I'm glad it's working now! :+1: 

closing this issue as solved.
