### ISSUE TITLE
Pifba

### ISSUE THREAD

**Issue by g-gibosky** [meleu/RetroPie-joystick-selection#44]
Hi Meleu. Huge fan of your work.

I'm back to retropie and for some reason pifba is inverting the controllers for a DragonRise (zero Delay).

I'm trying to use your script on raspberry pi zero but no dice. Doesn't matter the order, the controller keep on being switched.

There is a way to force the config of script on pifba? Thanks!

**Comment by meleu** [comment]
Sorry dude, I know pifba performance is better in a raspi zero, but unfortunately this script is aimed only for RetroArch emulators.
