### ISSUE TITLE
Where is the joystick selection in emulationstation.

### ISSUE THREAD

**Issue by zabagar** [meleu/RetroPie-joystick-selection#48]
The script automatically ran, initially, when I downloaded it with wget.  Now I’m in EmulationStation. Where do I find the joystick option here? Or do I need to rerun the script from a command prompt every time?

**Comment by zabagar** [comment]
> The script automatically ran, initially, when I downloaded it with wget. Now I’m in EmulationStation. Where do I find the joystick option here? Or do I need to rerun the script from a command prompt every time?

*UPDATE* - I found where the joystick script can be launched from inside emulation station. You need to add that to your documentation so people don’t have to blindly hunt for it.

**Comment by meleu** [comment]
Item 3 [here](https://github.com/meleu/RetroPie-joystick-selection?tab=readme-ov-file#installation)

**Comment by Brone88** [comment]
@zabagar where did you find it? I have the same problem

**Comment by meleu** [comment]
@Brone88 the [instructions in the README](https://github.com/meleu/RetroPie-joystick-selection?tab=readme-ov-file#installation) wasn't enough?

**Comment by Brone88** [comment]
@meleu not for me, actually. i've downloaded and launched the install.sh but i cannot see the option in the retropie configuration menu

**Comment by zabagar** [comment]
It’s the the Retropie Setup menu. After selecting RetroPie Setup, select “C - Configuration / Tools” then scroll down to “211 - Joystick selection”. Annoyingly this was not documented, at least back when I installed it. The author really needs to include that.
