### ISSUE TITLE
multiple joysticks with repeated names

### ISSUE THREAD

**Issue by meleu** [meleu/RetroPie-joystick-selection#5]
Selection by name is ON.

When multiple joysticks with repeated names are connected, the script puts a trailing " #N". If one of them is disconnected the number will change and the configs may not work as expected.

I have to deal with it.

**Comment by mmonkey** [comment]
I am also facing this issue, can you just have all joysticks add a trailing "#N"? So if I connect a single PS3 controller I get `PLAYSTATION(R)3 Controller #1` even if it is the only connect PS3 controller?

**Comment by meleu** [comment]
@mmonkey good suggestion, I'll try to work on that next week.

**Comment by meleu** [comment]
@mmonkey done as you suggested. Thanks!

It was tested by a RetroPie forum user: https://retropie.org.uk/forum/post/81054
