### ISSUE TITLE
Does not work properly with N64 games.

### ISSUE THREAD

**Issue by pdewilde** [meleu/RetroPie-joystick-selection#7]
N64 games seem to use some non-retroarch format by default. I was wondering if there was a way to make this work with n64 titles.

**Comment by meleu** [comment]
The description says "A script to let the user choose the controllers for **RetroArch** players 1-4". But, OK, I could try to add the N64 support if I knew how its config file work.

Could you show me how it is done currently. (I don't play N64 games)

**Comment by GottZ** [comment]
retropie uses a not so much retroarch compatible emulator for n64 so ye. worth taking a look.
