### ISSUE TITLE
script doesn't work when using "network share ROMs"

### ISSUE THREAD

**Issue by meleu** [meleu/RetroPie-joystick-selection#9]
Deal with "network share ROMs" scheme.
https://retropie.org.uk/forum/post/38328

**Comment by TooTallNate** [comment]
I'm not sure what this issue is about, but I run my ROMs over the internet via `sshfs` and there's no problems with this plugin. I can't even see how that would be related.

**Comment by meleu** [comment]
Not sure what's the problem with "network share ROMs". Closing until someone report something similar.
